server:
  port: ${IEXEC_CORE_PORT:18090}

spring:
  data:
    mongodb:
      database: iexec
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}

# all in milliseconds
detector:
  workerlost.period: 30000              # 30 s
  resultuploadtimeout.period: 30000     # 30 s
  dealwatcherreplay.period: 60000       # 1 min
  reveal.timeout.period: ${REVEAL_TIMEOUT_PERIOD:120000}       # 2 min
  reveal.unnotified.period: 30000       # 30s
  contribution.unnotified.period: 30000 # 30s
  contribution.timeout.period: 120000   # 2 min
  unstartedtx.period: 300000            # 5 min


wallet:
  encryptedFilePath: ${IEXEC_CORE_WALLET_PATH:./src/main/resources/wallet/encrypted-wallet_scheduler.json}
  password: ${IEXEC_CORE_WALLET_PASSWORD:whatever}

chain:
  id: ${IEXEC_CHAIN_ID:1337}
  privateAddress: ${IEXEC_PRIVATE_CHAIN_ADDRESS:http://localhost:8545}
  publicAddress: ${IEXEC_PUBLIC_CHAIN_ADDRESS:http://localhost:8545}
  hubAddress: ${IEXEC_HUB_ADDRESS:0x5df493e91aE066541C13d9a071137e850a56d609}
  poolAddress: ${POOL_ADDRESS:0x46f18edc77700277192ee6f8a4f0c0b889c845ca}
  startBlockNumber: ${IEXEC_START_BLOCK_NUMBER:0}

tee:
  enclaveChallenge: "0x3cb738d98d7a70e81e81b0811fae2452bca049bc"

workers:
  askForReplicatePeriod: ${IEXEC_ASK_REPLICATE_PERIOD:5000}
