server:
  port: ${IEXEC_CORE_PORT:18090}

spring:
  data:
    mongodb:
      database: iexec
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}

# all in milliseconds
detector:
  workerlost.period: 30000
  resultuploadtimeout.period: 30000

chain:
  address: ${IEXEC_CHAIN_ADDRESS:http://localhost:8545}
  poolAddress: "0xdBB8eA3FCc53B67521685DFa02d7C06313FdE0aA"