server:
  port: ${IEXEC_CORE_PORT:18090}

spring:
  data:
    mongodb:
      database: iexec
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}

# all in milliseconds
detector:
  workerlost.period: 30000              # 30 s
  resultuploadtimeout.period: 30000     # 30 s
  dealwatcherreplay.period: 60000       # 1 min
  reveal.timeout.period: ${REVEAL_TIMEOUT_PERIOD:120000}       # 2 min
  reveal.unnotified.period: 30000       # 30s
  contribution.unnotified.period: 30000 # 30s
  contribution.timeout.period: 120000   # 2 min
  unstartedtx.period: 300000            # 5 min


wallet:
  encryptedFilePath: ${IEXEC_CORE_WALLET_PATH:./src/main/resources/wallet/encrypted-wallet_scheduler.json}
  password: ${IEXEC_CORE_WALLET_PASSWORD:whatever}

chain:
  id: ${IEXEC_CHAIN_ID:17}
  privateAddress: ${IEXEC_PRIVATE_CHAIN_ADDRESS:http://localhost:8545}
  publicAddress: ${IEXEC_PUBLIC_CHAIN_ADDRESS:http://localhost:8545}
  hubAddress: ${IEXEC_HUB_ADDRESS:0x60E25C038D70A15364DAc11A042DB1dD7A2cccBC}
  poolAddress: ${POOL_ADDRESS:0xc0c288EC5242E7f53F6594DC7BADF417b69631Ba}
  startBlockNumber: ${IEXEC_START_BLOCK_NUMBER:0}

tee:
  enclaveChallenge: "0x3cb738d98d7a70e81e81b0811fae2452bca049bc"

workers:
  askForReplicatePeriod: ${IEXEC_ASK_REPLICATE_PERIOD:5000}


resultRepository:
  protocol: ${IEXEC_RESULT_REPOSITORY_PROTOCOL:http}
  ip: ${IEXEC_RESULT_REPOSITORY_IP:localhost}
  port: ${IEXEC_RESULT_REPOSITORY_PORT:18090}

