server:
  port: ${IEXEC_CORE_PORT:18090}

spring:
  data:
    mongodb:
      database: iexec
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}

# all in milliseconds
detector:
  workerlost.period: 30000
  resultuploadtimeout.period: 30000