server:
  port: ${IEXEC_CORE_PORT:18090}

spring:
  data:
    mongodb:
      database: iexec
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}

# all in milliseconds
detector:
  workerlost.period: 30000
  resultuploadtimeout.period: 30000




wallet:
  encryptedFilePath: ${IEXEC_CORE_WALLET_PATH:./src/main/resources/wallet/encrypted-wallet_scheduler.json}
  password: ${IEXEC_CORE_WALLET_PASSWORD:whatever}

chain:
  privateAddress: ${IEXEC_PRIVATE_CHAIN_ADDRESS:http://localhost:8545}
  publicAddress: ${IEXEC_PUBLIC_CHAIN_ADDRESS:http://localhost:8545}
  hubAddress: ${IEXEC_HUB_ADDRESS:0x5df493e91aE066541C13d9a071137e850a56d609}
  poolAddress: ${POOL_ADDRESS:0x46f18edc77700277192ee6f8a4f0c0b889c845ca}
